[build]
  command = "npm run build"
  publish = ".next"
  ignore = "git log -1 --pretty=%B | grep dependabot"

[build.environment]
  NEXT_TELEMETRY_DISABLED = "1"
  NODE_VERSION = "20"
  NEXT_CACHE = "true"
  CI = "true"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.processing]
  skip_processing = false 